group 'com.mapbox.maps.mapbox_maps'
version '1.0.0'

// 1. KITA WAJIB PAKAI INI AGAR VERSI KOTLIN TIDAK DOWNGRADE
buildscript {
    ext.kotlin_version = '1.9.22'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
        }
        maven {
            url 'https://api.mapbox.com/downloads/v2/snapshots/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                username = "mapbox"
                password = System.getenv("SDK_REGISTRY_TOKEN") ?: project.findProperty("SDK_REGISTRY_TOKEN") as String
            }
        }
    }
}

apply plugin: 'com.android.library'
// 2. KITA WAJIB PAKAI INI AGAR COMPILER BERJALAN
apply plugin: 'kotlin-android'

android {
    compileSdk flutter.compileSdkVersion

    namespace 'com.mapbox.maps.mapbox_maps'
    
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    
    defaultConfig {
        minSdkVersion 21
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}

dependencies {
    implementation "com.mapbox.maps:android-ndk27:11.28.0"

    implementation "androidx.annotation:annotation:1.5.0"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:2.6.2"
}
